slub/dfg-viewer

dfgviewer/plugins/sru/class.tx_dfgviewer_sru.php
dfgviewer/plugins/sru/class.tx_dfgviewer_sru_eid.php

- drop tag dv:fulltextsearch
- show proper message if no results have been found in SRU search

Fix sru details

---

dfgviewer/plugins/sru/tx_dfgviewer_sru.js
dfgviewer/res/js/script.js

Fix some issues found by PhpStorm

---

dfgviewer/modules/setup/locallang.xml
dfgviewer/res/js/script.js

Fix typos found by codespell

---

dfgviewer/Documentation/Index.rst

The pull-request contains a documentation of the installation of the `dfg-viewer` and is writen in ReST syntax.

Add installation documentation

---

.gitignore
dfgviewer/plugins/sru/class.tx_dfgviewer_sru.php
dfgviewer/res/frontend.css
dfgviewer/res/imagemanipulation.tmpl
dfgviewer/res/pageview.tmpl
dfgviewer/typoscript/constants.txt
dfgviewer/typoscript/setup.txt

Because of race conditions, the initialization code for the highlighting was moved to an window `load` event.

Running highlight text methode after an window load event

---

dfgviewer/res/frontend.css

Fulltext view comes now with text highlighting, spacing and some register lines for a better display of OCR text. This fixes also the word spacing problem between last and new line.

Optimize fulltext view 

---

dfgviewer/modules/setup/metadata.inc.php
dfgviewer/typoscript/setup.txt

This reverts commit 803dbe442c3bc54bfbe1e1f255cbdf46ffcecb1c.

Remove loadTCA()-calls and increment TYPO3 dependency

---

dfgviewer/modules/setup/locallang.xml
dfgviewer/modules/setup/metadata.inc.php

This adds the metadata configuration for archival objects.

Fix metadata issues

---

dfgviewer/Configuration/TCA/Overrides/sys_template.php
dfgviewer/Configuration/TypoScript/Page/page.ts
dfgviewer/ext_emconf.php
dfgviewer/ext_tables.php

Move TCA changes to proper place (as of 6.2)

---

LICENSE.txt

Update license text from GPL 2 to GPL 3

---

Resources/Private/Partials/PageView.html

Add condition if no page download is available in double-page-view

---

Build/Documentation/sphinx.sh
Classes/ViewHelpers/Format/SubStringLastViewHelper.php
Configuration/TypoScript/Plugins/kitodo.typoscript
Documentation/Index.rst
Resources/Private/JavaScript/dfgviewerScripts.js
Resources/Private/Partials/PageView.html

Fix some typos in comments and documentation (found by codespell)

---

Configuration/TypoScript/Page/header.typoscript
Resources/Public/Css/3DViewer/main.css
Resources/Public/Css/3DViewer/spinner.css

Add CSS for included 3D js viewer

---

Resources/Private/Plugins/Kitodo/Templates/View3D/Main.html
Resources/Public/Css/3DViewer/main.css

Changes made to the plugin after previous PRs were made.

Update css and template of 3DView plugin

---

Classes/Controller/SruController.php
Classes/Controller/UriController.php

Class Doc was renamed to AbstractDocument and function getDoc was renamed to getCurrentDocument

Use getCurrentDocument function

---

Configuration/TypoScript/Plugins/kitodo.typoscript

Revert "Rename cofiguration for tools to match changes in Kitodo Presentation"

---

Resources/Public/Css/3DViewer/main.css

only select canvas element in 3D DFG-Viewer not global

fix css selector for canvas element in 3d dfg-viewer

---

.github/workflows/npm-grunt.yml

Revert "Update from Node 12 to 18"

---

.github/workflows/npm-grunt.yml
.github/workflows/phpstan.yml
.gitignore
Build/package.json

It contains changes from https://github.com/slub/dfg-viewer/pull/291, https://github.com/slub/dfg-viewer/pull/292 and https://github.com/slub/dfg-viewer/pull/293.

Update Node JS

---

README.md

[MAINTENANCE] Add Maintainer to README

---

.github/workflows/documentation.yml

- Change git ref check from main to master

[BUGFIX] Update documentation.yml

---

.github/workflows/codeql.yml

[MAINTENANCE] Update codeql.yml

---

Resources/Private/Plugins/Kitodo/Templates/PageView/Main.html

- DFG-Viewer part to fix https://github.com/kitodo/kitodo-presentation/issues/1367
Depends on already merged PRs:
- https://github.com/kitodo/kitodo-presentation/pull/1500
- https://github.com/kitodo/kitodo-presentation/pull/1501

[BUGFIX] Define WILDWEBMIDI_REMOTE_PACKAGE_BASE constant in layout
