dfgviewer/modules/setup/locallang.xml
dfgviewer/modules/setup/metadata.inc.php
dfgviewer/plugins/uri/class.tx_dfgviewer_uri.php

Includes:
- distinction between legacy and granular URN
- display of publication run (fallback: publication date)
- reformat dates from YYYY-MM-DD to DD.MM.YYYY
- show title of superior work if applicable

Fixes for newspaper metadata handling

---

dfgviewer/ext_autoload.php
dfgviewer/ext_emconf.php
dfgviewer/ext_localconf.php
dfgviewer/ext_tables.php
dfgviewer/modules/setup/conf.php
dfgviewer/modules/setup/index.php
dfgviewer/modules/setup/metadata.inc.php
dfgviewer/modules/setup/structures.inc.php
dfgviewer/plugins/amd/class.tx_dfgviewer_amd.php
dfgviewer/plugins/gridpager/class.tx_dfgviewer_gridpager.php
dfgviewer/plugins/newspaper-calendar/class.tx_dfgviewer_newspaper-calendar.php
dfgviewer/plugins/newspaper-years/class.tx_dfgviewer_newspaper-years.php
dfgviewer/plugins/sru/class.tx_dfgviewer_sru.php
dfgviewer/plugins/sru/class.tx_dfgviewer_sru_eid.php
dfgviewer/plugins/uri/class.tx_dfgviewer_uri.php
dfgviewer/typoscript/setup.txt

In goobi/goobi-presentation code changes have been done to replace deprecated classes. The support for TYPO3 4.x has been dropped. The aim is to support TYPO3 from 6.2 up to 7.6.
As the dfgviewer extension relies on Goobi.Presentation, this work had to be done here too.

Replace deprecated classes according to changes in Goobi.Presentation

---

dfgviewer/Classes/ViewHelpers/DownloadLinksViewHelper.php
dfgviewer/Classes/ViewHelpers/XpathViewHelper.php

The test request described in dfgviewer/Documentation/Index.rst resulted
in an error on my system (Ubuntu 17.10, PHP 7.1.11, TYPO3 7.6.23):
"Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class
'SLUB\Dfgviewer\Helpers\GetDoc' not found"
Replacing 'SLUB' with 'Slub' in the GeneralUtility::makeInstance() call
in XPathViewHelper to exactly match the namespace solves the problem and
should not result in any problems on other systems.
Same change is applied to DownloadLinksViewHelper.

Fix strange case sensitivity issue

---

dfgviewer/Classes/ViewHelpers/XpathViewHelper.php
dfgviewer/Resources/Private/Partials/PageView.html

The fluid tag based viewhelper use already the htmlspecialchars()
function to escape special characters. Doing this in the dfgviewer xpath
viewhelper another time will result in rare cases in broken links.
e.g. &amp; is getting &amp;amp;
This patch adds an attribute "htmlspecialchars" which is TRUE by
default. Only in case of the link viewhelper, we set it to FALSE.

Avoid double htmlspecialchars() in link ViewHelper

---

Resources/Private/Language/de.locallang.xlf

Actually this adds only two german lables. But the complete file is rewritten by lfeditor in TYPO3 7.6.

add german translation of new language lables

---

package-lock.json
package.json

`grunt-clean` was outdated anyway and should have been changed to `grunt-contrib-clean`. But as we don’t use this one and `grunt-contrib-jshint` in our Grunt project we can remove them just as well.

Clean packages

---

Classes/Plugins/NewspaperCalendar.php

Error was caused by wrong initialization of variable as string instead of array. Since PHP 7.2 it causes error.

Fix wrong initialization as string

---

Resources/Private/Partials/PageView.html

This has been removed by #152. 
In case of URIs with reserved characters (`&amp;`) the URI will be encoded with htmlspecialchars twice.

Fix double escaping of catalogue links

---

Resources/Private/Partials/PageView.html

The METS field dv:ownerContact requires full URLs or mailto:-links. So
it's not correct to use the fluid link.email viewhelper.

'Fix wrong local-contact link (double mailto:)'

---

Resources/Private/Partials/PageView.html

This adds the two extra logos for aggregators and sponsors if available below the provider logo.
This will fix #178.

Add (again) aggregator and sponsor logos if available

---

Resources/Private/Partials/Piwik.html

Fix HTML5 warning by removing type attribut from script

---

Configuration/TypoScript/Config/config.typoscript

It is not needed, and setting it prevents installation in a subdirectory.

Remove config.absRefPrefix

---

Configuration/TypoScript/Page/header.typoscript

Corrects an error appearing after fixing following errors in presentation (https://github.com/kitodo/kitodo-presentation/issues/904) which occurred after PR (https://github.com/kitodo/kitodo-presentation/pull/877) which renamed the directories `Javascript` and `Flexforms` to camel-case in accordance with the TYPO3 Coding Guidelines.
In this case the extension tried to reach the path `/var/www/typo3/public/typo3conf/ext/dlf/Resources/Public/Javascript/jQueryUI/jquery-ui-mouse-slider-resizable-autocomplete.js` which had the non camel-case writing.

Fix dlf path: `Javascript` -> `JavaScript`

---

Resources/Private/JavaScript/dfgviewerScripts.js
Resources/Private/JavaScript/websiteScripts.js
Resources/Private/Less/all.less
Resources/Private/Less/components/audioplayer.less
Resources/Private/Less/components/controls.less
Resources/Private/Less/components/newspapers.less
Resources/Private/Less/components/normalize.less
Resources/Private/Less/components/sru.less
Resources/Private/Less/mixins.less
Resources/Private/Less/modules/fulltext.less
Resources/Private/Less/modules/gridview.less
Resources/Private/Less/modules/home.less
Resources/Private/Less/modules/sidebar.less
Resources/Private/Less/rte.less
Resources/Private/Less/structure.less
Resources/Private/Less/variables.less
Resources/Private/Less/website.less
Resources/Private/Less/website/content.less
Resources/Private/Less/website/header.less
Resources/Private/Less/website/home.less
Resources/Private/Less/website/structure.less

To comply with the basic licence GPL-3.0 guidelines, this pull request removes the old licence information from the LESS file headers ([see discussion](https://github.com/slub/dfg-viewer/pull/230#discussion_r1273563638)). In addition, the obsolete and unnecessary `//EOF` statement at the end of the LESS and JS files is removed.

Fix license comments in LESS file headers

---

Resources/Private/Less/structure.less

Corrects the position of the provider logo in fullscreen
Before clicking on the fullscreen icon
After clicking on the fullscreen icon
With the patch
To see the logo #221 is necessary

Fix position provider logo in fullscreen

---

Configuration/TypoScript/Plugins/kitodo.typoscript

This PR is a fix for problem reported here: https://github.com/kitodo/kitodo-presentation/issues/994

Rename cofiguration for tools to match changes in Kitodo Presentation

---

Resources/Private/Less/components/newspapers.less

Fix two details in the calendar view from newspapers:
- with an open day, display date above the underlaying text completely
- display the link box for the day in the last line of a month completely
When you click on a day in the calendar view of a newspaper, an overlay box with a date appears. The text underneath partially covers the date (at the bottom), this is corrected.
before:
after:
If the day is at the end of the month (last row of the table) the overlay box is only partially displayed, this is corrected.
before:
after:

Fix two details in the calendar view of newspapers

---

Build/phpstan.neon

This method is already renamed in master but not yet in 4.x branch.

Ignore this error until Kitodo.Presentation is not updated

---

Configuration/RequestMiddlewares.php

I'm not sure if this has any downsides, nor did I looked deeper why there is a false call, but this PR fixes the issue in #254

Fix call to `\Kitodo\Dlf\Middleware\SruMiddleware`

---

composer.json

Tested with TYPO3 11.x -all functionalities of DFG Viewer work.

Upgrade TYPO3 version to 11.5.36 and drop support for 9.5.31 in the composer file

---

Configuration/TypoScript/Plugins/kitodo.typoscript

Fixes https://github.com/kitodo/kitodo-presentation/issues/1151

Assign correct html id to `fullTextScrollElement`

---

composer.json

Allow typo3 core version up to the latest at the time ([11.5.34](https://get.typo3.org/version/11#get))

Bump `typo3/cms-core` version

---

Configuration/TCA/Overrides/tt_content.php

The first parameter $extensionName of method \TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin used to contain the vendor name in the past.
As the vendor name does not have any effect at all, it's usage has been marked as deprecated.
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.1/Deprecation-88995-CallingRegisterPluginWithVendorName.html

Fix calling registerPlugin with vendor name

---

.github/workflows/npm-grunt.yml
.github/workflows/phpstan.yml

Revert "Update GitHub actions which still used deprecated Node.js"

---

.github/workflows/documentation.yml

- Building and testing of documentation are still triggered by push and pull_request event
- Additionally the documentation is deployed to GitHub Pages when `master` branch is changed

[MAINTENANCE] Deploy documentation to GitHub Pages

---

Configuration/TypoScript/Plugins/dfgviewer.typoscript
Configuration/TypoScript/Plugins/kitodo.typoscript
Initialisation/data.xml

It should be `plugin.tx_dlf.persistence.storagePid`

[MAINTENANCE] Replace `config.storagePid` with `storagePid` config from `tx_dlf` plugin

---

.github/workflows/build-test-publish.yml

Instead of hard coding the slub repositories, this patch partially reverts commit a7890f63.

[MAINTENANCE] Fix workflow for build, test and publish

---

Initialisation/data.xml

- Update of tables `tx_dlf_formats`, `tx_dlf_metadata`, `tx_dlf_metadataformat` and `tx_dlf_metadatasubentries`
`https://.../viewer/?tx_dlf%5Bid%5D=https%3A%2F%2Fgit.uni-paderborn.de%2Fapi%2Fv4%2Fprojects%2F3852%2Frepository%2Ffiles%2FMETS_MODS%252Fmets_M0001.xml%2Fraw&no_cache=1`
> [!NOTE]  
> The difference in the number under "Angaben zum Original" is due to the feature that the source code does not output the empty metadata fields.

[MAINTENANCE]  Add metadata preset to data.xml
